#!/system/bin/sh

UKM=/data/UKM;
BB=$UKM/busybox;

UCI_CONFIG=$UKM/config.json;
UCI_ACTION=$UKM/actions/;
UCI_FILES=$UKM/files/;

if [ ! -f $UCI_CONFIG ]; then
	echo "{sections: [" > $UCI_CONFIG
	#$UKM/cpufreq.sh >> $UCI_CONFIG
	#echo "," >> $UCI_CONFIG
	$UKM/liveopp.sh >> $UCI_CONFIG
	echo "," >> $UCI_CONFIG
	$UKM/mali.sh >> $UCI_CONFIG
	echo "," >> $UCI_CONFIG
	$UKM/mali_vape.sh >> $UCI_CONFIG
	echo "]}" >> $UCI_CONFIG
fi

case "${1}" in
  config)
		$BB cat $UCI_CONFIG;;
  configpath)
		$BB echo $UCI_CONFIG;;
  actionpath)
		$BB echo $UCI_ACTION;;
	reset)
		$BB rm -f $UCI_CONFIG;;
esac;
